[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate",
  "rm -rf dist",
  "npx tsc --project tsconfig.json --outDir dist --declaration false",
  "ls -la dist/",
  "ls dist/main.js"
]

[start]
cmd = "npx prisma migrate deploy && node dist/main.js"
